### ISSUE TITLE
Add a progress bar while fetching the json(s)

### ISSUE THREAD

**Issue by danascape** [stormbreaker-project/StormCIApp#2]

**Comment by dinesh-thiyagarajan** [comment]
Hi can you pls assign this to me and give more context ? I can help you with this :)

**Comment by danascape** [comment]
Can you solve the issue within 2 days?

**Comment by dinesh-thiyagarajan** [comment]
Yeah I can try to close it within two days, but can you pls give me more context on this ? @danascape

**Comment by danascape** [comment]
the application fetches json data and displays it in 3 fragments. For the user to not be confused, I was thinking to add a progress bar on top while the json is being fetched @dineshkarthi95

**Comment by dinesh-thiyagarajan** [comment]
Ok cool got it I can pick it up then :)

**Comment by danascape** [comment]
Alright I'll assign it to you then 👍

**Comment by dinesh-thiyagarajan** [comment]
Hi won't be able to complete it thanks good luck @danascape

**Comment by danascape** [comment]
lol okay.

**Comment by PratyushSingh07** [comment]
Hey @danascape I would like to work on this issue
