### ISSUE TITLE
Revamp the UI

### ISSUE THREAD

**Issue by danascape** [stormbreaker-project/StormCIApp#4]
Aim to create this
![image](https://user-images.githubusercontent.com/40296389/197333991-078c5e6f-b9f8-4e80-aa47-f55b3173f308.png)

**Comment by danascape** [comment]
This will involve creating the vector icons as well as theming

**Comment by PratyushSingh07** [comment]
hey @danascape i would like to work on this issue

**Comment by danascape** [comment]
Moved over to https://github.com/danascape/StormCI/issues/7
